namespace:
  name: prod
 
image:
  repository: ajkris/techtrends 
  tag: latest
  pullPolicy: Always

replicaCount: 5

service:
  port: 4111
  targetPort: 7111
  protocol: TCP
  type: ClusterIP

resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"

ports:
  containerPort: 7111

livenessProbe:
  path: /healthz
  port: 7111

readinessProbe:
  path: /healthz
  port: 7111
